/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 4462d44209fcdf83ba20094d2848ce8f)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	APP_ORIGIN: string;
	LOCAL_CODEX_ENABLED: string;
	ALCHEMY_RUNTIME: string;
	WORKER_SELF_REFERENCE: Fetcher /* alchemy */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "LOCAL_CODEX_ENABLED" | "ALCHEMY_RUNTIME">> {}
}
